# Generated by Django 6.0.5 on 2026-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('ERP', 'ERP Related'), ('KRP', 'Kisan Fasal Rin'), ('Utility', 'Utility Apex Bank')], default='OTHER', max_length=10),
        ),
    ]
