# Generated by Django 6.0.5 on 2026-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_remove_task_description_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('ERP', 'ERP'), ('KRP', 'KRP'), ('Utility', 'Utility')], default='OTHER', max_length=10),
        ),
    ]
